
ALTER TABLE work_orders
  ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS payer_client_id INTEGER REFERENCES clients(id),
  ADD COLUMN IF NOT EXISTS payer_name VARCHAR(255) DEFAULT '';

ALTER TABLE work_order_works
  ADD COLUMN IF NOT EXISTS qty NUMERIC(10,2) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS norm_hours NUMERIC(10,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS norm_hour_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount NUMERIC(12,2) NOT NULL DEFAULT 0;
